"""add auditorias_conjunto table

¿Qué? Crea la tabla `auditorias_conjunto` (RQF-009): reciclador, conjunto,
      nivel de desempeño, tema educativo, descripción opcional, ruta de la
      foto de evidencia y fecha.
¿Para qué? Es la primera pieza de la auditoría que el Reciclador hace del
           desempeño de separación de un conjunto — decisión documentada
           en el issue #5 del backlog (una sola vía, global al conjunto,
           siempre con evidencia fotográfica).
¿Impacto? No destructiva — tabla nueva, no toca ninguna existente.

Revision ID: 5b14f46abde9
Revises: a4020a68b108
Create Date: 2026-08-27 11:57:18.800087

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ¿Qué? Identificadores que Alembic usa para construir el grafo de migraciones.
# ¿Para qué? down_revision apunta a la migración anterior; None indica que es la raíz.
# ¿Impacto? Alterar estos valores rompe el historial y puede causar errores al migrar.
revision: str = '5b14f46abde9'
down_revision: Union[str, Sequence[str], None] = 'a4020a68b108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos.

    ¿Qué? Crea `auditorias_conjunto` con sus llaves foráneas hacia
          `recicladores` y `conjuntos_residenciales` (ambas ON DELETE
          CASCADE — si se borra el reciclador o el conjunto, sus
          auditorías se borran con él, no quedan huérfanas).
    ¿Para qué? Soportar el envío de auditorías del reciclador (RQF-009).
    ¿Impacto? Segura en producción — solo agrega una tabla nueva.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias_conjunto',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('id_reciclador', sa.Integer(), nullable=False),
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.Column('nivel_desempeno', sa.String(length=20), nullable=False),
    sa.Column('tema_educativo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_evidencia', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conjunto_residencial'], ['conjuntos_residenciales.id_conjunto_residencial'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_reciclador'], ['recicladores.id_reciclador'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_index(op.f('ix_auditorias_conjunto_id_auditoria'), 'auditorias_conjunto', ['id_auditoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios aplicados por upgrade().

    ¿Qué? Elimina la tabla `auditorias_conjunto` y su índice.
    ¿Para qué? Deshacer esta migración si algo falla.
    ¿Impacto? Destructiva: se pierden todas las auditorías ya enviadas.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditorias_conjunto_id_auditoria'), table_name='auditorias_conjunto')
    op.drop_table('auditorias_conjunto')
    # ### end Alembic commands ###
