"""add id_referencia to notificaciones

¿Qué? Agrega `notificaciones.id_referencia` (entero, opcional).
¿Para qué? Puntero genérico al registro relacionado con la notificación —
           primer uso: AUDITORIA_PUBLICADA guarda ahí el id_auditoria, para
           que el botón "Ver" del frontend sepa cuál auditoría abrir sin
           adivinar por conjunto/fecha.
¿Impacto? No destructiva. Las notificaciones existentes quedan con
          id_referencia NULL — no aplica a ningún tipo anterior a esta.

Revision ID: 87f6e4a34b4c
Revises: 5b14f46abde9
Create Date: 2026-08-27 12:53:17.870004

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ¿Qué? Identificadores que Alembic usa para construir el grafo de migraciones.
# ¿Para qué? down_revision apunta a la migración anterior; None indica que es la raíz.
# ¿Impacto? Alterar estos valores rompe el historial y puede causar errores al migrar.
revision: str = '87f6e4a34b4c'
down_revision: Union[str, Sequence[str], None] = '5b14f46abde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos.

    ¿Qué? Agrega la columna `id_referencia` a `notificaciones`.
    ¿Para qué? Soportar el botón "Ver" de AUDITORIA_PUBLICADA.
    ¿Impacto? Segura en producción — columna nullable, sin backfill necesario.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificaciones', sa.Column('id_referencia', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios aplicados por upgrade().

    ¿Qué? Elimina la columna `id_referencia` de `notificaciones`.
    ¿Para qué? Deshacer esta migración si algo falla.
    ¿Impacto? Destructiva para ese dato puntual: las notificaciones
              AUDITORIA_PUBLICADA ya no podrían enlazar a su auditoría.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificaciones', 'id_referencia')
    # ### end Alembic commands ###
