"""add mostrar_contacto_directorio to recicladores

¿Qué? Agrega la columna booleana `mostrar_contacto_directorio` a la tabla
      `recicladores`, con valor por defecto `false`.
¿Para qué? El teléfono del reciclador se mostraba en el Directorio general
           (visible a cualquier usuario autenticado, no solo a su propio
           conjunto) sin que él hubiera dado consentimiento explícito para
           ese uso — Ley 1581 de 2012 (Habeas Data). Esta columna guarda
           esa decisión, que el reciclador activa desde su Perfil.
¿Impacto? No destructiva. Todos los recicladores existentes quedan en
          `false` (privacidad por defecto) — nadie pierde ni gana
          visibilidad de su teléfono automáticamente con este cambio.

Revision ID: a4020a68b108
Revises: 3a7c9e51d284
Create Date: 2026-08-26 11:37:12.019533

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ¿Qué? Identificadores que Alembic usa para construir el grafo de migraciones.
# ¿Para qué? down_revision apunta a la migración anterior; None indica que es la raíz.
# ¿Impacto? Alterar estos valores rompe el historial y puede causar errores al migrar.
revision: str = 'a4020a68b108'
down_revision: Union[str, Sequence[str], None] = '3a7c9e51d284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos.

    ¿Qué? Agrega `recicladores.mostrar_contacto_directorio` (booleano).
    ¿Para qué? Que el reciclador pueda decidir, desde su Perfil, si su
               teléfono aparece en el Directorio general.
    ¿Impacto? `server_default='false'` asegura que las filas existentes
              queden en el estado más privado, sin necesitar un UPDATE
              separado.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recicladores', sa.Column('mostrar_contacto_directorio', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios aplicados por upgrade().

    ¿Qué? Elimina la columna `recicladores.mostrar_contacto_directorio`.
    ¿Para qué? Deshacer esta migración si algo falla.
    ¿Impacto? Destructiva: se pierde la preferencia guardada por cada
              reciclador (vuelven a la app mostrando el teléfono según la
              lógica anterior a este cambio, sin distinción por usuario).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recicladores', 'mostrar_contacto_directorio')
    # ### end Alembic commands ###
