"""baseline: esquema inicial completo de VerdeApp

¿Qué? Crea las 18 tablas actuales del proyecto (roles, usuarios, residentes,
      recicladores, administradores de conjunto, conjuntos residenciales,
      unidades, localidades, puntos de acopio, contenido educativo,
      invitaciones, notificaciones y tokens de seguridad).
¿Para qué? Es la migración "punto de partida": a partir de aquí, cualquier
           cambio futuro al esquema se registra como una migración nueva en
           vez de depender de Base.metadata.create_all() o de editar
           init_db.sql a mano.
¿Impacto? Es segura para una base de datos NUEVA/vacía (la crea toda desde
          cero). En una base de datos que YA tenía estas tablas (creadas
          antes por create_all()), esta migración NO debe ejecutarse con
          "upgrade" — hay que marcarla como ya aplicada con
          "alembic stamp head" (ver instrucciones del equipo).

Revision ID: bd997ecd8d32
Revises: 
Create Date: 2026-08-05 16:15:47.937047

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ¿Qué? Identificadores que Alembic usa para construir el grafo de migraciones.
# ¿Para qué? down_revision apunta a la migración anterior; None indica que es la raíz.
# ¿Impacto? Alterar estos valores rompe el historial y puede causar errores al migrar.
revision: str = 'bd997ecd8d32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos.

    ¿Qué? [Describir qué tablas/columnas/índices se crean o modifican.]
    ¿Para qué? [Explicar el motivo del cambio.]
    ¿Impacto? [Indicar si afecta datos existentes o si es seguro en producción.]
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contenido_educativo',
    sa.Column('id_contenido', sa.Integer(), nullable=False),
    sa.Column('modulo_categoria', sa.String(length=255), nullable=False),
    sa.Column('titulo_tema', sa.String(length=255), nullable=False),
    sa.Column('cuerpo_texto', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_contenido')
    )
    op.create_index(op.f('ix_contenido_educativo_id_contenido'), 'contenido_educativo', ['id_contenido'], unique=False)
    op.create_table('localidades',
    sa.Column('id_localidad', sa.Integer(), nullable=False),
    sa.Column('nombre_localidad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_localidad')
    )
    op.create_index(op.f('ix_localidades_id_localidad'), 'localidades', ['id_localidad'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('tipo_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('tipo_rol')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('puntos_acopios',
    sa.Column('id_punto_acopio', sa.Integer(), nullable=False),
    sa.Column('id_localidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_encargado', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_localidad'], ['localidades.id_localidad'], ),
    sa.PrimaryKeyConstraint('id_punto_acopio')
    )
    op.create_index(op.f('ix_puntos_acopios_id_punto_acopio'), 'puntos_acopios', ['id_punto_acopio'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo_electronico'), 'usuarios', ['correo_electronico'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('administradores_conjunto',
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('numero_telefonico', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_administrador'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_administradores_conjunto_id_administrador'), 'administradores_conjunto', ['id_administrador'], unique=False)
    op.create_table('conjuntos_residenciales',
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.Column('id_localidad', sa.Integer(), nullable=False),
    sa.Column('nombre_conjunto', sa.String(length=255), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('verificado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_localidad'], ['localidades.id_localidad'], ),
    sa.ForeignKeyConstraint(['verificado_por_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conjunto_residencial')
    )
    op.create_index(op.f('ix_conjuntos_residenciales_id_conjunto_residencial'), 'conjuntos_residenciales', ['id_conjunto_residencial'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_table('invitaciones_admin_conjunto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('conjuntos_asignados', sa.String(length=255), nullable=False),
    sa.Column('invitado_por_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invitado_por_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('recicladores',
    sa.Column('id_reciclador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('localidad_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('asociacion', sa.String(length=255), nullable=True),
    sa.Column('numero_telefonico', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidades.id_localidad'], ),
    sa.PrimaryKeyConstraint('id_reciclador'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_recicladores_id_reciclador'), 'recicladores', ['id_reciclador'], unique=False)
    op.create_table('administradores_conjuntos',
    sa.Column('id_administrador_conjunto', sa.Integer(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador'], ['administradores_conjunto.id_administrador'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_conjunto_residencial'], ['conjuntos_residenciales.id_conjunto_residencial'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_administrador_conjunto')
    )
    op.create_index(op.f('ix_administradores_conjuntos_id_administrador_conjunto'), 'administradores_conjuntos', ['id_administrador_conjunto'], unique=False)
    op.create_table('invitaciones_reciclador_conjunto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_reciclador', sa.Integer(), nullable=False),
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.Column('invitado_por_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_conjunto_residencial'], ['conjuntos_residenciales.id_conjunto_residencial'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_reciclador'], ['recicladores.id_reciclador'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitado_por_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.Column('id_emisor', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conjunto_residencial'], ['conjuntos_residenciales.id_conjunto_residencial'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_emisor'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('recicladores_conjuntos',
    sa.Column('id_reciclador', sa.Integer(), nullable=False),
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_conjunto_residencial'], ['conjuntos_residenciales.id_conjunto_residencial'], ),
    sa.ForeignKeyConstraint(['id_reciclador'], ['recicladores.id_reciclador'], ),
    sa.PrimaryKeyConstraint('id_reciclador', 'id_conjunto_residencial')
    )
    op.create_table('unidades',
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('id_conjunto_residencial', sa.Integer(), nullable=False),
    sa.Column('torre', sa.String(length=50), nullable=False),
    sa.Column('apto', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_conjunto_residencial'], ['conjuntos_residenciales.id_conjunto_residencial'], ),
    sa.PrimaryKeyConstraint('id_unidad')
    )
    op.create_index(op.f('ix_unidades_id_unidad'), 'unidades', ['id_unidad'], unique=False)
    op.create_table('notificaciones_destinatarios',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('leida_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_notificacion'], ['notificaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion', 'id_usuario')
    )
    op.create_table('residentes',
    sa.Column('id_residente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('numero_telefonico', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_residente'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_residentes_id_residente'), 'residentes', ['id_residente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios aplicados por upgrade().

    ¿Qué? [Describir qué se elimina o restaura.]
    ¿Para qué? [Permitir deshacer esta migración si algo falla.]
    ¿Impacto? ¡VERIFICAR si la operación es DESTRUCTIVA antes de ejecutar en producción!
              El orden de las operaciones es inverso al de upgrade().
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_residentes_id_residente'), table_name='residentes')
    op.drop_table('residentes')
    op.drop_table('notificaciones_destinatarios')
    op.drop_index(op.f('ix_unidades_id_unidad'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_table('recicladores_conjuntos')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_table('invitaciones_reciclador_conjunto')
    op.drop_index(op.f('ix_administradores_conjuntos_id_administrador_conjunto'), table_name='administradores_conjuntos')
    op.drop_table('administradores_conjuntos')
    op.drop_index(op.f('ix_recicladores_id_reciclador'), table_name='recicladores')
    op.drop_table('recicladores')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('invitaciones_admin_conjunto')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_conjuntos_residenciales_id_conjunto_residencial'), table_name='conjuntos_residenciales')
    op.drop_table('conjuntos_residenciales')
    op.drop_index(op.f('ix_administradores_conjunto_id_administrador'), table_name='administradores_conjunto')
    op.drop_table('administradores_conjunto')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo_electronico'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_puntos_acopios_id_punto_acopio'), table_name='puntos_acopios')
    op.drop_table('puntos_acopios')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_localidades_id_localidad'), table_name='localidades')
    op.drop_table('localidades')
    op.drop_index(op.f('ix_contenido_educativo_id_contenido'), table_name='contenido_educativo')
    op.drop_table('contenido_educativo')
    # ### end Alembic commands ###
