"""add video and guia links to contenido educativo

¿Qué? Agrega las columnas url_video y url_guia a contenido_educativo.
¿Para qué? Permitir que el catálogo de contenido educativo (RQF-004/RQF-010)
           guarde el link al video de YouTube y a la guía de apoyo por
           separado del texto, para poder incrustar el reproductor y
           mostrar un botón de guía en el frontend.
¿Impacto? No destructiva — ambas columnas son opcionales (nullable), así
          que las filas existentes de contenido_educativo quedan intactas
          con estos campos en NULL.

Revision ID: fa49fa61a94a
Revises: dd3d66d7ceb6
Create Date: 2026-08-18 01:01:05.887796

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ¿Qué? Identificadores que Alembic usa para construir el grafo de migraciones.
# ¿Para qué? down_revision apunta a la migración anterior; None indica que es la raíz.
# ¿Impacto? Alterar estos valores rompe el historial y puede causar errores al migrar.
revision: str = 'fa49fa61a94a'
down_revision: Union[str, Sequence[str], None] = 'dd3d66d7ceb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos.

    ¿Qué? Agrega url_video y url_guia (ambas opcionales) a contenido_educativo.
    ¿Para qué? Separar los links de video/guía del texto libre del módulo.
    ¿Impacto? Segura en producción — no afecta filas existentes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contenido_educativo', sa.Column('url_video', sa.String(length=500), nullable=True))
    op.add_column('contenido_educativo', sa.Column('url_guia', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios aplicados por upgrade().

    ¿Qué? Elimina las columnas url_video y url_guia.
    ¿Para qué? Permitir deshacer esta migración si algo falla.
    ¿Impacto? Destructiva solo si ya se guardaron links en esas columnas —
              en ese caso se perderían al hacer downgrade.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contenido_educativo', 'url_guia')
    op.drop_column('contenido_educativo', 'url_video')
    # ### end Alembic commands ###
